<?php

/**
 * @file
 * Module file for concentration game.
 */

use Drupal\image\Entity\ImageStyle;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\Core\Url;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_theme().
 */
function concentration_game_theme() {
  $theme['block__concentrationblock'] = [
    'template' => 'block--concentrationblock',
  ];
  return $theme;
}

/**
 * {@inheritdoc}
 */
function concentration_game_block_view_alter(array &$build, BlockPluginInterface $block) {

  $content = $block->build()['#block_content'];
  if (!empty($content) && ($content->bundle() === "concentration")) {
    if (empty($content->get('field_concentration_face_down')->getValue())) {
      $facedown_image_mid = '';
    }
    
    else {
      $facedown_image_mid = $content->get('field_concentration_face_down')->getValue()[0]['target_id'];
    }

    $facedown_image = get_image_data_concentration_game($facedown_image_mid, 'concentration_image_200x300');
    $images = $content->get('field_concentration_game_images')->getValue();
    $image_info = [];
    $user_id = \Drupal::currentUser()->id();

    foreach ($images as $image) {
      $image_id = $image['target_id'];
      $data = get_image_data_concentration_game($image_id, 'concentration_image_100x125');
      if($user_id == $data['owner_id']){
      $data = get_image_data_concentration_game($image_id, 'concentration_image_200x300');
      $image_info[] = [
        'id' => $image_id,
        'url' => $data['url'],
        'alt' => $data['alt'],
        'owner_id' => $data['owner_id'],
      ];
    }
    }
    $cardAmount = 8;
    if (count($image_info) < $cardAmount) {

      $admin_user = \Drupal::entityTypeManager()->getStorage('user')->loadByProperties(['name' => 'admin']);
      $admin_user_id = !empty($admin_user) ? reset($admin_user)->id() : 0;
    while(count($image_info)< $cardAmount){
      foreach ($images as $image) {
        if (count($image_info) >= $cardAmount) {
          break 2; 
        }
        $image_id = $image['target_id'];
        $data = get_image_data_concentration_game($image_id, 'concentration_image_100x125');
        if($admin_user_id == $data['owner_id']){
        $image_info[] = [
          'id' => $image_id,
          'url' => $data['url'],
          'alt' => $data['alt'],
          'owner_id' => $data['owner_id'],
        ];
      }
      }
    }

    }

    $uniqueid = $content->bundle().'_'.$content->id().'_'.rand();
    $build['#attached']['drupalSettings']['gameBoxes']['concentration'][$uniqueid] = [
      'cards' => $image_info,
      'facedown' => $facedown_image,
      'uniqueID' => $uniqueid,
    ];
  }
}

/**
 * {@inheritdoc}
 */
function concentration_game_theme_suggestions_block_alter(&$suggestions, &$vars) {
  if (
      !empty($vars['elements']['content']) 
      && !empty($vars['elements']['content']['#block_content'])
      && $vars['elements']['content']['#block_content']->bundle() === "concentration"
    ) {
    $suggestions[] = 'block__concentrationblock';
  }
}

/**
 * {@inheritdoc}
 */
function concentration_game_preprocess_block__concentrationblock(&$variables) {
  //global $cardAmount;
  $content = $variables['elements']['content']['#block_content'];
  $images = $content->get('field_concentration_game_images')->getValue();

  if (!empty($content->get('field_concentration_instruction')->getValue())) {
    $instruction = $content->get('field_concentration_instruction')->getValue()[0]['value'];
  }
  
  else {
    $instruction = '';
  }

  if (!empty($content->get('field_concentration_title')->getValue())) {
    $title = $content->get('field_concentration_title')->getValue()[0]['value'];
  }
  
  else {
    $title = '';
  }

  if (!empty($content->get('field_board_dimension')->getValue())) {
    $dimension = $content->get('field_board_dimension')->getValue()[0]['value'];
  }
  
  else {
    $dimension = 'fourbyfour';
  }

  if (!empty($content->get('field_hints')->getValue())) {
    $hints = $content->get('field_hints')->getValue()[0]['value'];
  }
  
  else {
    $hints = 0;
  }
  
  if (!empty($content->get('field_hint_clarity')->getValue())) {
    $hintClarity = strval($content->get('field_hint_clarity')->getValue()[0]['value']);
  }
  
  else {
    $hintClarity = "0px";
  }
  
  if (!empty($content->get('field_hint_color')->getValue())) {
    $hintColor = strval($content->get('field_hint_color')->getValue()[0]['value']);
  }
  
  else {
    $hintColor = "darkgreen";
  }
  
  if (!empty($content->get('field_concentration_play_again')->getValue())) {
    $playAgain = $content->get('field_concentration_play_again')->getValue()[0]['value'];
  }
  
  else {
    $playAgain = '';
  }


  $link = [];
  if (!empty($content->get('field_concentration_continu_link')->getValue())) {
    $link = [
      'title' => $content->get('field_concentration_continu_link')->getValue()[0]['title'],
      'url' => Url::fromUri($content->get('field_concentration_continu_link')->getValue()[0]['uri'])->toString(),
    ];
  }

  $uniqueid = $content->bundle().'_'.$content->id();
  $uniqueid = $uniqueid."_".rand();
  $variables['#attached']['library'][] = 'concentration_game/game_concentration';
  $variables['instruction'] = $instruction;
  $variables['title'] = $title;
  $variables['link'] = $link;
  $variables['playAgain'] = $playAgain;
  $variables['do_render'] = count($images) >= 8 ? TRUE : FALSE;
  $key = array_keys($variables['elements']['#attached']['drupalSettings']['gameBoxes']['concentration'])[0];
  $unique_id = $variables['elements']['#attached']['drupalSettings']['gameBoxes']['concentration'][$key]['uniqueID'];
  $variables['uniqueID'] = $unique_id;
  $variables['gridSetup'] = $dimension;
  $variables['hintLimit'] = $hints;
  $variables['hintClarity'] = $hintClarity;
  $variables['hintColor'] = $hintColor;
  $variables['user_id'] = \Drupal::currentUser()->id();
}

/**
 * Callback to get image url.
 *
 * @param int $media_id
 *   Image media id.
 * @param string $image_style
 *   Image Style.
 *
 * @return array
 *   Array of url and alt text.
 */
function get_image_data_concentration_game($media_id, $image_style = '') {
  $data = [
    'url' => NULL,
    'alt' => NULL,
    'owner_id' => NULL,
  ];

  if (!$media_id) {
    return $data;
  }

  $media = Media::load($media_id);
  $img = $media->get('thumbnail')->getValue()['0'];

  if (isset($img['target_id'])) {
    $file = File::load($img['target_id']);
    $url = $file->createFileUrl();
    if ($image_style) {
      $style = ImageStyle::load($image_style);
      $url = $style ? $style->buildUrl($file->getFileUri()) : $url;
    }

    $data = [
      'url' => $url,
      'alt' => $img['alt'],
      'owner_id' => $file->getOwnerId(),
    ];
  }

  return $data;
}


