<?php

/**
 * @file
 * Module file for concentration game.
 */

use Drupal\image\Entity\ImageStyle;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\Core\Url;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_theme().
 */
function concentration_game_theme() {
  $theme['block__concentrationblock'] = [
    'template' => 'block--concentrationblock',
  ];
  return $theme;
}

/**
 * {@inheritdoc}
 */
function concentration_game_block_view_alter(array &$build, BlockPluginInterface $block) {
  $content = $block->build()['#block_content'];
  if (!empty($content) && ($content->bundle() === "concentration")) {
    if (empty($content->get('field_concentration_face_down')->getValue())) {
      $facedown_image_mid = '';
    }
    
    else {
      $facedown_image_mid = $content->get('field_concentration_face_down')->getValue()[0]['target_id'];
    }

    if (empty($content->get('field_concentration_success_img')->getValue())) {
      $success_image_mid = '';
    }
    
    else {
      $success_image_mid = $content->get('field_concentration_success_img')->getValue()[0]['target_id'];
    }

    $facedown_image = get_image_data_concentration_game($facedown_image_mid, 'concentration_image_100x125');
    $success_image = get_image_data_concentration_game($success_image_mid, 'concentration_success_image_500x500');
    $images = $content->get('field_concentration_game_images')->getValue();
    $image_info = [];
    
    foreach ($images as $image) {
      $image_id = $image['target_id'];
      $data = get_image_data_concentration_game($image_id, 'concentration_image_100x125');
      $image_info[] = [
        'id' => $image_id,
        'url' => $data['url'],
        'alt' => $data['alt'],
      ];
    }

    $uniqueid = $content->bundle().'_'.$content->id().'_'.rand();
    $build['#attached']['drupalSettings']['gameBoxes']['concentration'][$uniqueid] = [
      'cards' => $image_info,
      'facedown' => $facedown_image,
      'success_image' => $success_image,
      'uniqueID' => $uniqueid,
    ];
  }
}

/**
 * {@inheritdoc}
 */
function concentration_game_theme_suggestions_block_alter(&$suggestions, &$vars) {
  if (!empty($vars['elements']['content']) && !empty($vars['elements']['content']['#block_content'])
    && ($vars['elements']['content']['#block_content']->bundle() === "concentration")) {
    $suggestions[] = 'block__concentrationblock';
  }
}

/**
 * {@inheritdoc}
 */
function concentration_game_preprocess_block__concentrationblock(&$variables) {
  $content = $variables['elements']['content']['#block_content'];
  $images = $content->get('field_concentration_game_images')->getValue();

  if (!empty($content->get('field_concentration_instruction')->getValue())) {
    $instruction = $content->get('field_concentration_instruction')->getValue()[0]['value'];
  }
  
  else {
    $instruction = '';
  }

  if (!empty($content->get('field_concentration_title')->getValue())) {
    $title = $content->get('field_concentration_title')->getValue()[0]['value'];
  }
  
  else {
    $title = '';
  }

  if (!empty($content->get('field_concentration_play_again')->getValue())) {
    $playAgain = $content->get('field_concentration_play_again')->getValue()[0]['value'];
  }
  
  else {
    $playAgain = '';
  }

  $link = [];
  if (!empty($content->get('field_concentration_continu_link')->getValue())) {
    $link = [
      'title' => $content->get('field_concentration_continu_link')->getValue()[0]['title'],
      'url' => Url::fromUri($content->get('field_concentration_continu_link')->getValue()[0]['uri'])->toString(),
    ];
  }

  $uniqueid = $content->bundle().'_'.$content->id();
  $uniqueid = $uniqueid."_".rand();
  $variables['#attached']['library'][] = 'concentration_game/game_concentration';
  $variables['instruction'] = $instruction;
  $variables['title'] = $title;
  $variables['link'] = $link;
  $variables['playAgain'] = $playAgain;
  $variables['do_render'] = count($images) >= 8 ? TRUE : FALSE;
  $key = array_keys($variables['elements']['#attached']['drupalSettings']['gameBoxes']['concentration'])[0];
  $unique_id = $variables['elements']['#attached']['drupalSettings']['gameBoxes']['concentration'][$key]['uniqueID'];
  $variables['uniqueID'] = $unique_id;
  $variables['gridSetup'] = 'threebytwo';
}

/**
 * Callback to get image url.
 *
 * @param int $mid
 *   Image media id.
 * @param string $image_style
 *   Image Style.
 *
 * @return array
 *   Array of url and alt text.
 */
function get_image_data_concentration_game($mid, $image_style = '') {
  $data = [
    'url' => NULL,
    'alt' => NULL,
  ];
  
  if (!$mid) {
    return $data;
  }

  $media = Media::load($mid);
  $img = $media->get('thumbnail')->getValue()['0'];

  if (isset($img['target_id'])) {
    $file = File::load($img['target_id']);
    $url = $file->createFileUrl();
    if ($image_style) {
      $style = ImageStyle::load($image_style);
      $url = $style ? $style->buildUrl($file->getFileUri()) : $url;
    }

    $data = [
      'url' => $url,
      'alt' => $img['alt'],
    ];
  }

  return $data;
}
